-- Skema PostgreSQL untuk aplikasi Kunjungan Studi.
-- Jalankan melalui Supabase CLI (`supabase db push`) atau SQL Editor.

create table if not exists users (
  id bigint generated by default as identity primary key,
  nama text not null,
  email text not null unique,
  password_hash text not null,
  telepon text,
  instansi text,
  alamat text,
  role text not null default 'PEMOHON',
  aktif integer not null default 1,
  foto text,
  created_at timestamptz not null default now()
);

create table if not exists sessions (
  id text primary key,
  user_id bigint not null references users(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists rooms (
  id bigint generated by default as identity primary key,
  kode text not null unique,
  nama text not null,
  kapasitas integer not null default 0,
  lokasi text,
  fasilitas text,
  status text not null default 'TERSEDIA',
  keterangan text,
  created_at timestamptz not null default now()
);

create table if not exists room_qr_codes (
  id bigint generated by default as identity primary key,
  room_id bigint not null references rooms(id) on delete cascade,
  tipe text not null default 'PENGADUAN',
  token text not null unique,
  aktif integer not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists visit_applications (
  id bigint generated by default as identity primary key,
  nomor text not null unique,
  user_id bigint not null references users(id) on delete cascade,
  nama_kelompok text not null,
  asal_instansi text not null,
  jenis_instansi text,
  jumlah_peserta integer not null,
  tujuan text not null,
  tanggal_usulan date not null,
  waktu_mulai_usulan time not null,
  waktu_selesai_usulan time not null,
  penanggung_jawab text,
  telepon_pj text,
  catatan text,
  status text not null default 'DRAFT',
  catatan_admin text,
  alasan_keputusan text,
  verified_by bigint references users(id),
  verified_at timestamptz,
  jenis_kunjungan text not null default 'RESMI',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists documents (
  id bigint generated by default as identity primary key,
  application_id bigint not null references visit_applications(id) on delete cascade,
  jenis text not null,
  nama_file text not null,
  url text,
  catatan text,
  berkas text,
  created_at timestamptz not null default now()
);

create table if not exists visitors (
  id bigint generated by default as identity primary key,
  application_id bigint not null references visit_applications(id) on delete cascade,
  nama text not null,
  identitas text,
  jenis text not null default 'PESERTA',
  keterangan text,
  created_at timestamptz not null default now()
);

create table if not exists visit_schedules (
  id bigint generated by default as identity primary key,
  application_id bigint not null references visit_applications(id) on delete cascade,
  room_id bigint references rooms(id),
  tanggal date not null,
  waktu_mulai time not null,
  waktu_selesai time not null,
  penanggung_jawab text,
  status text not null default 'TERJADWAL',
  catatan text,
  created_by bigint references users(id),
  created_at timestamptz not null default now()
);

create table if not exists attendance (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references visit_schedules(id) on delete cascade,
  application_id bigint not null references visit_applications(id) on delete cascade,
  room_id bigint references rooms(id),
  visitor_id bigint references visitors(id) on delete set null,
  nama_peserta text not null,
  metode text not null default 'PILIH_NAMA',
  checkin_at timestamptz not null default now(),
  checkout_at timestamptz,
  catatan text
);

create table if not exists facility_reports (
  id bigint generated by default as identity primary key,
  nomor text not null unique,
  room_id bigint not null references rooms(id),
  application_id bigint references visit_applications(id) on delete set null,
  kategori text not null,
  deskripsi text not null,
  urgensi text not null default 'SEDANG',
  pelapor_nama text,
  pelapor_kontak text,
  anonim integer not null default 0,
  foto_url text,
  sumber text not null default 'QR',
  status text not null default 'DIAJUKAN',
  petugas text,
  selesai_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists report_actions (
  id bigint generated by default as identity primary key,
  report_id bigint not null references facility_reports(id) on delete cascade,
  admin_id bigint references users(id),
  status_dari text,
  status_ke text not null,
  petugas text,
  catatan text,
  created_at timestamptz not null default now()
);

create table if not exists notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references users(id) on delete cascade,
  judul text not null,
  pesan text not null,
  link text,
  dibaca integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists audit_logs (
  id bigint generated by default as identity primary key,
  user_id bigint references users(id) on delete set null,
  aktor text not null,
  aksi text not null,
  entitas text,
  entitas_id text,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_user on visit_applications(user_id);
create index if not exists idx_app_status on visit_applications(status);
create index if not exists idx_sch_room on visit_schedules(room_id, tanggal);
create index if not exists idx_att_sch on attendance(schedule_id);
create index if not exists idx_rep_room on facility_reports(room_id);
create index if not exists idx_rep_status on facility_reports(status);
create index if not exists idx_notif_user on notifications(user_id, dibaca);

-- Aplikasi melakukan autentikasi sendiri. Semua tabel tetap ditutup dari role
-- anon/authenticated; koneksi server memakai rahasia DATABASE_URL.
alter table users enable row level security;
alter table sessions enable row level security;
alter table rooms enable row level security;
alter table room_qr_codes enable row level security;
alter table visit_applications enable row level security;
alter table documents enable row level security;
alter table visitors enable row level security;
alter table visit_schedules enable row level security;
alter table attendance enable row level security;
alter table facility_reports enable row level security;
alter table report_actions enable row level security;
alter table notifications enable row level security;
alter table audit_logs enable row level security;
